//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorCarReport
{
    using DoctorCarReport.util;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Windows;
    
    public partial class drcardriveEntities : DbContext
    {
        private string p;

        public drcardriveEntities()
            : base("name=drcardriveEntities")
        {
        }

        public drcardriveEntities(string connString):base(connString)
        {
            
        }

        

       
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_car> tbl_car { get; set; }
        public virtual DbSet<tbl_car_Tombstone> tbl_car_Tombstone { get; set; }
        public virtual DbSet<tbl_drive> tbl_drive { get; set; }
        public virtual DbSet<tbl_drive_medicine> tbl_drive_medicine { get; set; }
        public virtual DbSet<tbl_drive_medicine_Tombstone> tbl_drive_medicine_Tombstone { get; set; }
        public virtual DbSet<tbl_drive_staff> tbl_drive_staff { get; set; }
        public virtual DbSet<tbl_drive_staff_Tombstone> tbl_drive_staff_Tombstone { get; set; }
        public virtual DbSet<tbl_drive_Tombstone> tbl_drive_Tombstone { get; set; }
        public virtual DbSet<tbl_drive_village> tbl_drive_village { get; set; }
        public virtual DbSet<tbl_drive_village_Tombstone> tbl_drive_village_Tombstone { get; set; }
        public virtual DbSet<tbl_expense_desc> tbl_expense_desc { get; set; }
        public virtual DbSet<tbl_expense_desc_Tombstone> tbl_expense_desc_Tombstone { get; set; }
        public virtual DbSet<tbl_expenses> tbl_expenses { get; set; }
        public virtual DbSet<tbl_expenses_Tombstone> tbl_expenses_Tombstone { get; set; }
        public virtual DbSet<tbl_fuel> tbl_fuel { get; set; }
        public virtual DbSet<tbl_fuel_Tombstone> tbl_fuel_Tombstone { get; set; }
        public virtual DbSet<tbl_issue_medicine> tbl_issue_medicine { get; set; }
        public virtual DbSet<tbl_issue_medicine_Tombstone> tbl_issue_medicine_Tombstone { get; set; }
        public virtual DbSet<tbl_places> tbl_places { get; set; }
        public virtual DbSet<tbl_places_Tombstone> tbl_places_Tombstone { get; set; }
        public virtual DbSet<tbl_staff> tbl_staff { get; set; }
        public virtual DbSet<tbl_staff_Tombstone> tbl_staff_Tombstone { get; set; }
        public virtual DbSet<tbl_weather> tbl_weather { get; set; }
        public virtual DbSet<tbl_weather_Tombstone> tbl_weather_Tombstone { get; set; }
    }
}
