//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorCarReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_drive
    {
        public string ID { get; set; }
        public string DRIVER_NAME { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<double> START_ODOMETER { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<double> END_ODOMETER { get; set; }
        public string REMARK { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> INSERT_DATETIME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string FKY_CAR { get; set; }
        public string FROM { get; set; }
        public string TO { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
