//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorCarReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_places
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> ARRIVAL_DATE { get; set; }
        public Nullable<double> ARRIVAL_ODOMETER { get; set; }
        public Nullable<System.DateTime> DEPARTURE_DATE { get; set; }
        public Nullable<double> DEPARTURE_ODOMETER { get; set; }
        public Nullable<int> NUMBER_PATIENT { get; set; }
        public Nullable<int> NUMBER_DOCTORS { get; set; }
        public Nullable<int> NUMBER_PARAMEDICS { get; set; }
        public string REMARK { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> INSERT_DATETIME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATETIME { get; set; }
        public string FKY_DRIVE { get; set; }
        public string FKY_VILLAGE { get; set; }
        public string VILLAGE_NAME { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
